### PR TITLE
Release 1.0.3

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Release 1.0.3. Will deliver https://github.com/PrestaShop/ps_distributionapiclient/pull/10. Please note it works only with 8.0.2, not 8.0.1 or 8.0.0 .
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| How to test?      | ~
| Possible impacts? | ~

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @matks and @atomiix 👋 

On `develop` branch, Distribution API v1.0.3 is automatically updated (I didn't have to click on Upgrade button)
Screenshot 2022-09-28 at 10 49 13

On `8.0.x` branch, the number version is incorrect NOK: (I think I need @matks for this issue)
Screenshot 2022-09-28 at 14 11 41
But after clicking on Upgrade button, it is well updated to v1.0.3 OK:
Screenshot 2022-09-28 at 14 13 30

**Manual upgrade:** (for this issue @atomiix could you help ?)
I fully delete psgdpr module 1.4.2 (module+folder+database). I install v1.4.0, I have this exception (click on Previous button, no more error and the module is well installed):
Screenshot 2022-09-28 at 14 25 22

Manual upgrade module psgdpr from v1.4.0 to v1.4.1 NOK -> directly upgrades to 1.4.2.

Also tried to fully delete the module, installed psgdpr v1.4.1, upgrade with zip of 1.4.2 : OK

**Upgrade via Upgrade button:**
psgdpr 1.4.0 to 1.4.2 OK
Screenshot 2022-09-28 at 14 37 08

**Upgrade via Upgrade All button:**
customersignin 2.0.4 to 2.0.5 OK
psgdpr 1.4.1 to 1.4.2 OK
Screenshot 2022-09-28 at 14 32 31

**Action buttons** Install / Uninstall are OK

Am I missing something ?
Thanks!

**Comment by matks** [comment]
This Release PR is actually blocked by https://github.com/PrestaShop/PrestaShop/issues/29542

@atomiix explored the issues detected by @florine2623 and is now blocked by the above bug

**Comment by matks** [comment]
Release blocked by https://github.com/PrestaShop/PrestaShop/issues/31093

**Comment by atomiix** [comment]
I'm wondering if we should not update the min `ps_versions_compliancy` to `8.0.2` because upgrading to `1.0.3` in `< 8.0.2` will fail

**Comment by kpodemski** [comment]
@atomiix uhh, does it mean that people on 8.0.2 won't see dist API 1.0.3? does it work like that?

**Comment by atomiix** [comment]
@kpodemski people on 8.0.1 won't see ps_distributionapiclient 1.0.3, but starting 8.0.2, everything should be normal

**Comment by matthieu-rolland** [comment]
I've set the `ps_versions_compliancy` to 8.0.2, the PR has been merged

**Review by matthieu-rolland — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by hibatallahAouadni — COMMENTED** [review]
Hello @matks 

I encounter an issue with 8.1.x and develop, see the attached screen record below:

[api_12.webm](https://user-images.githubusercontent.com/23308427/221624227-86a1fe61-2fd5-4979-83e1-129c473d9fbc.webm)

When I uninstall a module for example "Best brands" and then I refresh the page, try to find the module, it doesn't display any thing :disappointed: 
I tried with psgdpr module, also the same problem.

Please check and feedback.

Thanks!

**Comment by matks** [comment]
> Hello @hibatallahAouadni you mention 8.1.x and develop, what happens for 8.0.x ?
> 
> I think for 8.1.x and develop it actually might be expected: Distribution API does not provide informations for modules for PrestaShop 8.1.0 and 9.0.0 right now 🤔 . So it seems logical.

Ha 😅 important information: this release is supposed to fix bug https://github.com/PrestaShop/PrestaShop/issues/29594 that we aim to deliver in PrestaShop 8.0.2 . But this new version of the module only works with 8.0.2 not 8.0.1 or 8.0.0

So if you try to install it on 8.0.1 it should fail ;) you must make sure it's a 8.0.2

**Review by hibatallahAouadni — APPROVED** [review]
Hello @matks 

LGTM, QA :heavy_check_mark: 

[release_api.webm](https://user-images.githubusercontent.com/23308427/221882435-946a5575-2919-49cb-ae74-6477001150e1.webm)

Thanks @matthieu-rolland & @atomiix for your help :pray: :superhero: 

Thanks

**Comment by matthieu-rolland** [comment]
thank you @hibatallahAouadni , thank you @matks !

**Comment by matks** [comment]
Thank you @hibatallahAouadni and @matthieu-rolland 😉

**Pull request merged**
