### PR TITLE
Provide only necessary info from distribution API when module is on disk

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | This PR aims to not provide some information from the distribution API if the module is on the disk, especially the `version` that is displayed in the module manager.
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes PrestaShop/PrestaShop#28436
| How to test?      | Please see PrestaShop/PrestaShop#28436
| Possible impacts? |

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
@atomiix How do we test this?

**Review by Progi1984 — APPROVED** [review]

**Comment by atomiix** [comment]
@matks I think trying to reproduce the related issue and see that it should be solved thanks to this PR is enough? 🤔

**Comment by matks** [comment]
> I think trying to reproduce the related issue and see that it should be solved thanks to this PR is enough? 🤔

I have no idea why I wrote this on 10th of May. Either I totally missed the point or I was thinking it was something else 😅

**Review by sLorenzini — APPROVED** [review]
hello @atomiix,

Tested on develop branch
PHP version 7.2

Tested with blockwishlist and ps_emailalerts modules.
Use 2.0.1 version for blockwishlist instead of 2.1.0 (last version)
Use 2.3.2 version for ps_emailalerts instead of 2.3.3 (last version)
Tested with multistore enable and disable.

Steps:
- Uninstall those modules 
- Checked and unchecked "Optional: delete module folder after uninstall." checkbox
- Upload those modules
- Good version is displayed and the upgrade alert

QA approved ✅

**Comment by Progi1984** [comment]
Thanks @atomiix & @sLorenzini

**Pull request merged**
