### PR TITLE
Update Master branch

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Apply modifications from main branch into master branch
| Type?             | pm
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | none
| Sponsor company   | PrestaShop SA
| How to test?      | none to test, main has already been tested ?

### CODE REVIEW

**Review by lartist — APPROVED** [review]

**Review by matks — APPROVED** [review]
For context: in October 2022 with @atomiix we found out that this repository having no `master` branch broke a script that would parse all modules registered in https://github.com/prestashop/prestashop-modules/ .

The script is looking for a `master` branch and it is responsible for fetching modules for releases distribution for PrestaShop < 8.0.0 .

So for now we have, on this repository
- the `main` branch that contains the code for release
- the `master`branch which must mirror `main` and it's used for the above script

**Review by nicosomb — APPROVED** [review]

**Comment by Hlavtox** [comment]
@matks What about using `master` branch like all other repos? :trollface:

**Comment by matks** [comment]
> @matks What about using `master` branch like all other repos? :trollface:

I'm not against it, it was just a move initiated by https://github.com/github/renaming

**Comment by nicosomb** [comment]
> I'm not against it, it was just a move initiated by https://github.com/github/renaming

`main` is now the default name for main branch. If we have `main` branch, we should delete `master` one. 
It's a non sense to keep the two branches.

**Comment by matks** [comment]
@nicosomb The problem is that the script that parse all modules registered in https://github.com/prestashop/prestashop-modules/ is sitting all alone on an old server and yet it is responsible for distributing module releases for PrestaShop < 8.0.0 😅 so modifying it is unfortunately a complex task (obviously no tests!)

So I agree with you: it makes no sense. It's not supposed to make sense. It's a simple price we pay for backward compatibility for users of old PrestaShop software. Little gift for the user community 😉 .

**Pull request merged**
